
- name: Install the Java 
  yum:
    name: java
- name: Install  Git
  yum:
    name: git
- name: Install  Docker
  yum:
    name: docker
- name: Restarting docker  service
  service:
    name: docker
    enabled: yes
    state: restarted
- name: Restarting docker  service
  shell: chmod 666 /var/run/docker.sock

- name: Download Jenkins repository file
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins repository GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present
  
- name: Install Jenkins
  yum:
    name: jenkins
    state: latest
  
- name: Restarting Jenkins service
  service:
    name: jenkins
    enabled: yes
    state: restarted
  notify: Generate Jenkins One Time Password

- name: Running SonarQube Container [Port 9000]
  shell: docker run -d --name sonar -p 9000:9000 sonarqube:lts-community