apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-backend-image:43
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URL
          value: "mongo.svc.cluster.local:27017"