apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-backend-image
        env:
        - name: MONGO_URL
          value: "mongodb://apiUser:apiPassword@mongo-0.mongo:27017/todos?authSource=admin"
        ports:
        - containerPort: 3000
