apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image:28058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image: 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image:2827 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image: 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image:28058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image: 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image:28278 # Ensure to build and push this image: 058264315018.dkr.ecr.eu-west-3.amazonaws.com/nti-frontend-image:28 to your registry
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer